/*
 * PhotoPanel.java, part of the JYMAG package.
 *
 * Copyright (C) 2013-2024 Bogdan Drozdowski, bogdro (at) users . sourceforge . net
 * License: GNU General Public License, v3+
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package bogdrosoft.jymag.gui.panels;

import bogdrosoft.jymag.PhoneElement;
import bogdrosoft.jymag.Utils;
import bogdrosoft.jymag.gui.JYMAGTransferHandler;
import bogdrosoft.jymag.gui.MainWindow;
import bogdrosoft.jymag.gui.UiUtils;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 * This class is the photos' panel in the JYMAG program.
 * @author Bogdan Drozdowski
 */
public class PhotoPanel extends javax.swing.JPanel implements JYMAGTab
{
	private static final long serialVersionUID = 87L;

	private volatile MainWindow mw;

	private Vector<PhoneElement> currentPhotoElements;
	private JFileChooser downloadFC;
	private JFileChooser uploadPictFC;
	private String destDirName;

	// i18n stuff:
	private static final ResourceBundle MSGS
		= ResourceBundle.getBundle("bogdrosoft/jymag/i18n/MainWindow");
	private static final String PICT_TYPES_STRING
		= MSGS.getString("Supported_pictures");

	/** Creates new form PhotoPanel */
	public PhotoPanel()
	{
		initComponents();

		photoTable.setFillsViewportHeight (true);
		photoTable.setDragEnabled (true);
		/* Make clicking on the table header select all the table's rows */
		photoTable.getTableHeader ().addMouseListener (
			new UiUtils.TableMouseListener (photoTable));
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings({"unchecked", "rawtypes"})
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                jScrollPane1 = new javax.swing.JScrollPane();
                photoTable = new javax.swing.JTable();
                downloadPhotoBut = new javax.swing.JButton();
                uploadPhotoBut = new javax.swing.JButton();
                deletePhotoBut = new javax.swing.JButton();
                getPhotoListBut = new javax.swing.JButton();

                setBackground(new java.awt.Color(184, 242, 255));

                jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

                photoTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][]
                        {

                        },
                        new String []
                        {
                                java.util.ResourceBundle.getBundle("bogdrosoft/jymag/i18n/MainWindow").getString("Name")
                        }
                )
                {
                        private static final long serialVersionUID = 66L;
                        Class[] types = new Class []
                        {
                                java.lang.String.class
                        };
                        boolean[] canEdit = new boolean []
                        {
                                false
                        };

                        public Class getColumnClass(int columnIndex)
                        {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex)
                        {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(photoTable);

                downloadPhotoBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bogdrosoft/jymag/rsrc/download.png"))); // NOI18N
                java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bogdrosoft/jymag/i18n/MainWindow"); // NOI18N
                downloadPhotoBut.setText(bundle.getString("Download_selected")); // NOI18N
                downloadPhotoBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                downloadPhotoButdownloadButActionPerformed(evt);
                        }
                });

                uploadPhotoBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bogdrosoft/jymag/rsrc/upload.png"))); // NOI18N
                uploadPhotoBut.setText(bundle.getString("Upload")); // NOI18N
                uploadPhotoBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                uploadPhotoButActionPerformed(evt);
                        }
                });

                deletePhotoBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bogdrosoft/jymag/rsrc/delete.png"))); // NOI18N
                deletePhotoBut.setText(bundle.getString("Delete_selected")); // NOI18N
                deletePhotoBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                deletePhotoButdeleteButActionPerformed(evt);
                        }
                });

                getPhotoListBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bogdrosoft/jymag/rsrc/get-list.png"))); // NOI18N
                getPhotoListBut.setText(bundle.getString("Get_list")); // NOI18N
                getPhotoListBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                getPhotoListButActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1012, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(getPhotoListBut)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(downloadPhotoBut)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(uploadPhotoBut)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(deletePhotoBut)))
                                        .addContainerGap()))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 265, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(getPhotoListBut)
                                                .addComponent(downloadPhotoBut)
                                                .addComponent(uploadPhotoBut)
                                                .addComponent(deletePhotoBut))
                                        .addGap(25, 25, 25)))
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deletePhotoBut, downloadPhotoBut, getPhotoListBut, uploadPhotoBut});

        }// </editor-fold>//GEN-END:initComponents

	private void getPhotoListButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_getPhotoListButActionPerformed
	{//GEN-HEADEREND:event_getPhotoListButActionPerformed

		if ( currentPhotoElements == null )
		{
			currentPhotoElements = new Vector<PhoneElement> (1);
		}

		PanelUtils.putListInTable (mw, "PICTURES",	// NOI18N
			(DefaultTableModel) photoTable.getModel (),
			currentPhotoElements);
	}//GEN-LAST:event_getPhotoListButActionPerformed

	private void downloadPhotoButdownloadButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_downloadPhotoButdownloadButActionPerformed
	{//GEN-HEADEREND:event_downloadPhotoButdownloadButActionPerformed

		if ( downloadFC == null )
		{
			downloadFC = new JFileChooser ();
		}
		
		PanelUtils.download(mw, photoTable.getSelectedRows (),
			currentPhotoElements, downloadFC, destDirName);
	}//GEN-LAST:event_downloadPhotoButdownloadButActionPerformed

	private void uploadPhotoButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_uploadPhotoButActionPerformed
	{//GEN-HEADEREND:event_uploadPhotoButActionPerformed

		if ( uploadPictFC == null )
		{
			uploadPictFC = UiUtils.createOpenFileChooser (
				PICT_TYPES_STRING, Utils.getPhotofileIDs ());
		}

		PanelUtils.upload(mw, uploadPictFC);
	}//GEN-LAST:event_uploadPhotoButActionPerformed

	private void deletePhotoButdeleteButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_deletePhotoButdeleteButActionPerformed
	{//GEN-HEADEREND:event_deletePhotoButdeleteButActionPerformed
		
		PanelUtils.delete(mw, photoTable.getSelectedRows (),
			currentPhotoElements);
	}//GEN-LAST:event_deletePhotoButdeleteButActionPerformed

	@Override
	public void setDestDir (String destDir)
	{
		destDirName = destDir;
	}

	@Override
	public void setMainWindow (MainWindow mainWindow)
	{
		mw = mainWindow;
		photoTable.setTransferHandler (new JYMAGTransferHandler (mw));
	}

	@Override
	public void setFontSizeSpin (JSpinner fontSizeSpinner)
	{
		// not needed
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton deletePhotoBut;
        private javax.swing.JButton downloadPhotoBut;
        private javax.swing.JButton getPhotoListBut;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable photoTable;
        private javax.swing.JButton uploadPhotoBut;
        // End of variables declaration//GEN-END:variables

}
