/*
 * RingtonePanel.java, part of the JYMAG package.
 *
 * Copyright (C) 2013-2024 Bogdan Drozdowski, bogdro (at) users . sourceforge . net
 * License: GNU General Public License, v3+
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package BogDroSoft.jymag.gui.panels;

import BogDroSoft.jymag.PhoneElement;
import BogDroSoft.jymag.Utils;
import BogDroSoft.jymag.gui.JYMAGTransferHandler;
import BogDroSoft.jymag.gui.MainWindow;
import BogDroSoft.jymag.gui.UiUtils;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 * This class is the ringtones' panel in the JYMAG program.
 * @author Bogdan Drozdowski
 */
public class RingtonePanel extends javax.swing.JPanel implements JYMAGTab
{
	private static final long serialVersionUID = 88L;

	private volatile MainWindow mw;

	private Vector<PhoneElement> currentRingElements;
	private JFileChooser downloadFC;
	private JFileChooser uploadRingFC;
	private String destDirName;

	// i18n stuff:
	private static final ResourceBundle mwBundle = ResourceBundle.getBundle("BogDroSoft/jymag/i18n/MainWindow");
	private static final String SOUND_TYPES_STRING = mwBundle.getString("Supported_sounds");

	/** Creates new form RingtonePanel */
	public RingtonePanel()
	{
		initComponents();

		ringTable.setFillsViewportHeight (true);
		ringTable.setDragEnabled (true);
		/* Make clicking on the table header select all the table's rows */
		ringTable.getTableHeader ().addMouseListener (
			new UiUtils.TableMouseListener (ringTable));
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings({"unchecked", "rawtypes"})
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                jScrollPane2 = new javax.swing.JScrollPane();
                ringTable = new javax.swing.JTable();
                getRingListBut = new javax.swing.JButton();
                downloadRingBut = new javax.swing.JButton();
                uploadRingBut = new javax.swing.JButton();
                deleteRingBut = new javax.swing.JButton();

                setBackground(new java.awt.Color(179, 255, 179));

                jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 0));

                ringTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][]
                        {

                        },
                        new String []
                        {
                                java.util.ResourceBundle.getBundle("BogDroSoft/jymag/i18n/MainWindow").getString("Name")
                        }
                )
                {
                        private static final long serialVersionUID = 67L;
                        Class[] types = new Class []
                        {
                                java.lang.String.class
                        };
                        boolean[] canEdit = new boolean []
                        {
                                false
                        };

                        public Class getColumnClass(int columnIndex)
                        {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex)
                        {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane2.setViewportView(ringTable);

                getRingListBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BogDroSoft/jymag/rsrc/get-list.png"))); // NOI18N
                java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("BogDroSoft/jymag/i18n/MainWindow"); // NOI18N
                getRingListBut.setText(bundle.getString("Get_list")); // NOI18N
                getRingListBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                getRingListButActionPerformed(evt);
                        }
                });

                downloadRingBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BogDroSoft/jymag/rsrc/download.png"))); // NOI18N
                downloadRingBut.setText(bundle.getString("Download_selected")); // NOI18N
                downloadRingBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                downloadRingButdownloadButActionPerformed(evt);
                        }
                });

                uploadRingBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BogDroSoft/jymag/rsrc/upload.png"))); // NOI18N
                uploadRingBut.setText(bundle.getString("Upload")); // NOI18N
                uploadRingBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                uploadRingButActionPerformed(evt);
                        }
                });

                deleteRingBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BogDroSoft/jymag/rsrc/delete.png"))); // NOI18N
                deleteRingBut.setText(bundle.getString("Delete_selected")); // NOI18N
                deleteRingBut.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                deleteRingButdeleteButActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1012, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(getRingListBut)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(downloadRingBut)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(uploadRingBut)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(deleteRingBut)))
                                        .addContainerGap()))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 265, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(getRingListBut)
                                                .addComponent(downloadRingBut)
                                                .addComponent(uploadRingBut)
                                                .addComponent(deleteRingBut))
                                        .addGap(25, 25, 25)))
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteRingBut, downloadRingBut, getRingListBut, uploadRingBut});

        }// </editor-fold>//GEN-END:initComponents

	private void getRingListButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_getRingListButActionPerformed
	{//GEN-HEADEREND:event_getRingListButActionPerformed

		if ( currentRingElements == null )
		{
			currentRingElements = new Vector<PhoneElement> (1);
		}

		PanelUtils.putListInTable (mw, "RINGTONES",	// NOI18N
			(DefaultTableModel) ringTable.getModel (),
			currentRingElements);
	}//GEN-LAST:event_getRingListButActionPerformed

	private void downloadRingButdownloadButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_downloadRingButdownloadButActionPerformed
	{//GEN-HEADEREND:event_downloadRingButdownloadButActionPerformed

		if ( downloadFC == null )
		{
			downloadFC = new JFileChooser ();
		}

		PanelUtils.download(mw, ringTable.getSelectedRows (),
			currentRingElements, downloadFC, destDirName);
	}//GEN-LAST:event_downloadRingButdownloadButActionPerformed

	private void uploadRingButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_uploadRingButActionPerformed
	{//GEN-HEADEREND:event_uploadRingButActionPerformed

		if ( uploadRingFC == null )
		{
			uploadRingFC = UiUtils.createOpenFileChooser (
				SOUND_TYPES_STRING, Utils.getRingfileIDs ());
		}

		PanelUtils.upload(mw, uploadRingFC);
	}//GEN-LAST:event_uploadRingButActionPerformed

	private void deleteRingButdeleteButActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteRingButdeleteButActionPerformed
	{//GEN-HEADEREND:event_deleteRingButdeleteButActionPerformed
		
		PanelUtils.delete(mw, ringTable.getSelectedRows (),
			currentRingElements);
	}//GEN-LAST:event_deleteRingButdeleteButActionPerformed

	@Override
	public void setDestDir (String destDir)
	{
		destDirName = destDir;
	}

	@Override
	public void setMainWindow (MainWindow mainWindow)
	{
		mw = mainWindow;
		ringTable.setTransferHandler (new JYMAGTransferHandler (mw));
	}

	@Override
	public void setFontSizeSpin (JSpinner fontSizeSpinner)
	{
		// not needed
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton deleteRingBut;
        private javax.swing.JButton downloadRingBut;
        private javax.swing.JButton getRingListBut;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable ringTable;
        private javax.swing.JButton uploadRingBut;
        // End of variables declaration//GEN-END:variables

}
